version: '3'

services:
  appdb:
    build:
      context: ./src/main/DB/
      dockerfile: Dockerfile
    image: appraisaldb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password123

  gbt:
    build:
      context: ./src/main/
      dockerfile: Dockerfile
    image: gbt
    ports:
      - '80:80'
    links:
      - appservice:appservice

  appservice:
    build:
      context: ./
      dockerfile: Dockerfile
    image: appraisalservice
    ports:
      - '8080:8080'
    depends_on:
      - appdb
    links:
      - appdb:appdb